version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-china # 容器名称
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat_room
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234567
      TZ: Asia/Shanghai
    ports:
      - '12000:3306'
    volumes: # 数据持久化
      - /home/mysql/db:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '12005:6379'
    volumes:
      - /home/mysql/redis:/data # 将主机的 /data/redis 目录挂载到容器内的 /data 目录，用于持久化数据
    command: redis-server --appendonly yes # 开启持久化模式
