version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-china
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/:/data # 将主机的 /data/redis 目录挂载到容器内的 /data 目录，用于持久化数据
    command: redis-server --appendonly yes # 开启持久化模式
volumes:
  mysql-data:
