db:
  mysql:
    host: 127.0.0.1
    prot: 3306

# JWT
JWT:
  secret: 'fsdFSD@#$24+9*-'
  expiresIn: '4h'

# redis
REDIS:
  password: '123456'
  prot: 6379

# 启动端口
PORT: 8768

# 静态文件目录
PREFIX: '/files/'
# 访问地址
